services:
  - type: web
    name: brand-story-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: PORT
        value: 10000